---
abstract: 'Simple API support for Catalyst apps'
author:
  - 'Jay Kuri (jayk) C<< <jayk@cpan.org> >>.'
  - 'Jay Kuri <jayk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  MooseX::Declare: 0
  Test::More: 0
  Try::Tiny: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-SimpleAPI
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst::Runtime: 5.80029
  JSON::Any: 0
  JSON::XS: 0
  LWP::UserAgent: 0
  Moose: 0
  MooseX::MethodAttributes: 0
  URI: 0
  namespace::autoclean: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/wreis/CatalystX-SimpleAPI.git
version: 0.01
